/////////////////////////////////////////////////////////////////////////
// Javascript file generated by ctc2html v2.6
// Copyright (c) 2006-2010 Testwell Oy
/////////////////////////////////////////////////////////////////////////
target=location.hash;
function load(){
if(target=="#a1"){
parent.index.location="indexC.html#a1";
parent.profile.location="indexD1.html";
}
if(target=="#a2"){
parent.index.location="indexC.html#a2";
parent.profile.location="indexD2.html";
}
if(target=="#a3"){
parent.index.location="indexC.html#a3";
parent.profile.location="indexD3.html";
}
if(target=="#a4"){
parent.index.location="indexC.html#a4";
parent.profile.location="indexD4.html";
}
}
function load2(){
if(target=="#ad1"){
parent.index2.location="indexH.html#ad1";
parent.functions.location="indexB1.html";
}
if(target=="#ad2"){
parent.index2.location="indexH.html#ad2";
parent.functions.location="indexB2.html";
}
if(target=="#ad2"){
parent.index2.location="indexH.html#ad2";
parent.functions.location="indexB2.html";
}
if(target=="#ad2"){
parent.index2.location="indexH.html#ad2";
parent.functions.location="indexB2.html";
}
}
